name: GA-Run-All-Rust-Test-On-Master

on:
  workflow_run:
    workflows: ['Docker Image CI']
    types:
      - completed

jobs:
  GA-All-Rust-Test:
    runs-on: ga-test-runner-check-rust-tests
    steps:
      - name: üêß  Check out repository code
        uses: actions/checkout@v3
        with:
          ssh: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: 'Launch script on latest'
        run: |
          ./tests/test_exercises.sh \
          -real \
          -n
